services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflowpass
      POSTGRES_DB: taskflow
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .        # ðŸ‘ˆ ahora el contexto es la raÃ­z del proyecto
      dockerfile: ./app/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/usr/src/app  # mount project root so package `app` is available
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://taskflow:taskflowpass@db:5432/taskflow
      SECRET_KEY: "super-secret-change-me"
    depends_on:
      - db

volumes:
  pgdata:
